#ifndef ENGINE_CORE_METHODHELPERS_H
#define ENGINE_CORE_METHODHELPERS_H

#define RSUCCESS(r) (r == RVAL::R_OK)
#define RFAILURE(r) (r != RVAL::R_OK)

namespace Engine 
{
namespace Core 
{
		
const enum RVAL {
	R_OK				= 0,
	R_FAILED			= 1,

	R_EM_KEY_BLANK,
	R_EM_EFFECT_NULL,
	R_EM_KEY_EXISTS,
	R_EM_INVALID_FILE,

	R_RR_CREATE_DEVICE_FAILED,
	R_RR_CREATE_SWAP_CHAIN_FAILED,
	R_RR_CREATE_RENDER_TARGET_FAILED,
	R_RR_CREATE_DEPTH_STENCIL_FAILED,
	R_RR_CREATE_VIEWPORT_FAILED
};

}
}

#endif